
all	: 
	@g++ -o myapp_libcamera myapp_libcamera.cpp /usr/lib/aarch64-linux-gnu/libboost_program_options.so.1.74.0 /usr/lib/aarch64-linux-gnu/libcamera-base.so /usr/lib/aarch64-linux-gnu/libcamera.so  -I/usr/include/libcamera/libcamera/ -I/usr/include/libcamera/ -std=c++17





